# Jekyll configuration
name: Engineering Guidelines
description: Collection of Prixz's Best Practices. This is a formal document that establishes uniform engineering or technical criteria, methods, processes, and practices.
url: "https://farmacia-logistica.github.io/EngineeringGuidelines/index.html"
markdown: kramdown
kramdown:
  parse_block_html: true
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
